### ISSUE TITLE
Conflict with bootstrap class .close.

### ISSUE THREAD

**Issue by elfet** [ccampbell/rainbow#101]
It have conflict with Bootstrap class ".close".

**Comment by stoeffel** [comment]
Thanks @jblashill

**Comment by jpdevries** [comment]
:+1: on `rainbow-` prefix but even more so, I think the larger issue at hand is selectors like `pre` or `pre code` in the theme CSS files are too loose. 

If you use `<pre>` or `<code>` outside of rainbow, it will muck up your site styles. Isn't that silly? Seems like rainbow should require being wrapped in a `.rainbow` selector or utilize [Scoped CSS](http://css-tricks.com/saving-the-day-with-scoped-css/) in some way.

**Comment by kswope** [comment]
The classes that rainbow inserts into the pre tags are crazy common and general.  "string", "keyword", "close", "comment".  How could these not conflict with other sources, whether its a hugely popular framework or just somebodies little css file?

**Comment by ccampbell** [comment]
@kswope it is because I am applying them only inside of a `pre` tag.  Please look at the code before throwing out an accusation :smile:

https://github.com/ccampbell/rainbow/blob/master/themes/monokai.css

**Comment by kswope** [comment]
That keeps you from polluting other css, but it does nothing to prevent other css from polluting yours!

Another thing to think about.  Some css selectors, like from frameworks like bootstrap, is chosen to be easy for users, so they have priority over css that is inserted into the DOM programmatically.  The css inserted by rainbow could have been random strings and it wouldn't even matter.

Now, because it looks like you are taking a stand on principals or something, using rainbow is too hazardous!  Every time I add some new css, mine or third party, I have to double check that its not screwing with rainbow.

**Comment by inclusiv1** [comment]
I used the following, similar to @jblashill 

```css
pre .support.close {
	float:none;
	font-size: inherit;
	font-weight: inherit;
	line-height: inherit;
	color: inherit;
	text-shadow: none;
	opacity: 1;
}

```
This will basically inherit, but some inherited stuff might not work and again you will need to override depending on your theme.
