### ISSUE TITLE
nbsp; converted to regular space

### ISSUE THREAD

**Issue by drewmcdowell** [ccampbell/rainbow#179]
When `&nbsp;` is written in HTML, the output is just a space.  `&nbsp;` should be kept as part of the code.

**Comment by ccampbell** [comment]
You have to write out the actual entity `&amp;nbsp;` if you want it to show up in the code I think, but I will take a look later

**Comment by drewmcdowell** [comment]
Thanks for the quick reply.  You're right, that does output correctly. However it would be great if it wasn't required to edit the original code in this way.

**Comment by ccampbell** [comment]
There is only so much that can be done for html in the browser.  If you put in regular tags `<p></p>` the browser parses them as html tags.  The code should be put in the page as `&lt;p&gt;&lt;/p&gt;`.  

There is code in rainbow to handle the entity encoding, but it might just be something to do with how the browser parses it before the code runs.  I will try to look into this later.

https://github.com/ccampbell/rainbow/blob/ae87ac6fc82a2b0c4c8b2d42fe7fde1d3a431ce0/js/rainbow.js#L174

**Comment by ccampbell** [comment]
Closing this out since there is not really much that can be done. I could try to always escape html entities, but then if you actually wanted to put in an `&nbsp;` space you wouldn't be able to. 

I think it is a bit less magical if you are required to always escape entities yourself before highlighting. You could write a helper function to do this
